### ISSUE TITLE
Expected to decode Bool but found a number instead.

### ISSUE THREAD

**Issue by 417-72KI** [417-72KI/BuildConfig.swift#63]
### Error
```
BuildConfigSwiftDemo/BuildConfig.generated.swift:42: Fatal error: Invalid data (. cause: typeMismatch(Swift.Bool, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "api_version", intValue: nil)], debugDescription: "Expected to decode Bool but found a number instead.", underlyingError: nil))
```

### Config
```yml
is_debug: true
environment: debug
api_version: 1
```

### Expected
- `api_version` should be parsed as Int
